# Generated by Django 4.2.30 on 2026-05-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=20),
        ),
    ]
